/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 健康检查 — systemd / Caddy 探活用
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio
         * @description 完整持仓快照（v1 兼容输出，前端无感）：现金 CNY/AUD + 黄金 + NDQ.AX
         */
        get: operations["get_portfolio_api_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Holdings
         * @description v2 通用持仓列表：cash dict + holdings 数组（含实时 quote + 计算 P&L）
         */
        get: operations["get_holdings_api_holdings_get"];
        put?: never;
        /**
         * Add Holding
         * @description 新增持仓（任意 yfinance symbol）。symbol 已存在 → 409
         */
        post: operations["add_holding_api_holdings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/holdings/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Holding
         * @description 部分字段更新单个 holding（仅传非空字段会被改写）
         */
        put: operations["update_holding_api_holdings__symbol__put"];
        post?: never;
        /**
         * Delete Holding
         * @description 删除持仓。units > 0 时拒绝（避免数据丢失），用户必须先卖光或显式 set units=0
         */
        delete: operations["delete_holding_api_holdings__symbol__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/symbols/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Symbols
         * @description 通过 yfinance Search 搜索 symbol（零 token 配置）。
         *     用户输入 'apple' / '腾讯' / 'TSLA' 都能用
         */
        get: operations["search_symbols_api_symbols_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Strategy
         * @description 当前投资策略：目标比例 + 各资产 cap / 点差 / 费率
         */
        get: operations["get_strategy_api_strategy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Gold
         * @description 黄金持仓 + 实时金价 + 浙商参考价（独立端点，前端可单独刷新而不重拉 NDQ）
         */
        get: operations["get_gold_api_gold_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ndq": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ndq
         * @description NDQ.AX 持仓 + 实时价 + 日变化（v2: 从 pm.holdings 读）
         */
        get: operations["get_ndq_api_ndq_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get History
         * @description 交易流水（portfolio_history.jsonl），按时间倒序返回最近 limit 条
         */
        get: operations["get_history_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pnl_chart.svg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pnl Chart
         * @description jobs/pnl_snapshot 每 2h 工作日自动生成的 PnL 趋势图（vs 8 个基准）。
         *     SVG 只含百分比，不暴露绝对金额
         */
        get: operations["get_pnl_chart_api_pnl_chart_svg_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Daily
         * @description daily/<date>.md 完整 markdown，前端用 react-markdown 渲染
         */
        get: operations["get_daily_api_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deposit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deposit
         * @description 存入现金（v2: 任意币种 cash dict 写入）。RMW 单锁，并发安全
         */
        post: operations["deposit_api_deposit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Withdraw
         * @description 取出现金（v2: 任意币种 + 负数校验）。
         *     余额不足默认 400 拒绝（PM 关切：避免 AUD -6894 类似事故）
         */
        post: operations["withdraw_api_withdraw_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gold/buy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gold Buy
         * @description 记录黄金买入（v2: holdings.upsert("GC=F")）
         */
        post: operations["gold_buy_api_gold_buy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gold/sell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gold Sell
         * @description 记录黄金卖出（v2: holdings.find + cash["CNY"] 联动）
         */
        post: operations["gold_sell_api_gold_sell_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gold/set": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gold Set
         * @description 直接设置黄金克数（v2: holdings GC=F units 直接覆盖；均价不变）
         */
        post: operations["gold_set_api_gold_set_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gold/offset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gold Offset
         * @description 报当日浙商克价 → 反推点差 offset → 写回 strategy.md。系统自学习浙商溢价
         */
        post: operations["gold_offset_api_gold_offset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/committee/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Committee Run
         * @description v3 真并行委员会触发（统一端点）
         *
         *     - 不传 symbols → 跑 strategy.target_assets 全部
         *     - 传单个 symbol → 单资产快速版（旧 run_single 等效）
         *     - 多资产并行：macro 共享 1 次，每个资产独立线程跑（内部 Round 1/2 也并行）
         *     - max_debate_rounds 默认 4 真讨论；旧 daily_report cron 走单独路径不受影响
         */
        post: operations["committee_run_api_committee_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/committee/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Committee Status
         * @description 查询委员会任务状态（pending → running → done/error）
         */
        get: operations["committee_status_api_committee__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/committee/live/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Committee Live
         * @description SSE 流式推送 task 状态变化（前端 EventSource 订阅）
         *
         *     用法（前端）：
         *         const es = new EventSource(`/api/committee/live/${taskId}`);
         *         es.addEventListener('progress', (e) => { ... });
         *         es.addEventListener('done', () => es.close());
         *
         *     每 2s 重读 status.json 如有变化推送 progress event；
         *     每 25s 推送 `: keepalive` 注释防 CF Access 5 min idle 超时
         */
        get: operations["committee_live_api_committee_live__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategy/allocations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Allocations
         * @description 改资产配置目标（stock/cash 比例）。两者之和必须 ≈ 1（schema 强约束）
         */
        put: operations["put_allocations_api_strategy_allocations_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategy/asset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Target Asset
         * @description 新增 target_asset。symbol 不能与现有重复
         */
        post: operations["add_target_asset_api_strategy_asset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategy/asset/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Target Asset
         * @description 更新单个 target_asset 的部分字段（仅传非空字段会被改写）
         */
        put: operations["update_target_asset_api_strategy_asset__symbol__put"];
        post?: never;
        /**
         * Delete Target Asset
         * @description 删除 target_asset。schema 要求至少剩 1 个，否则 400
         */
        delete: operations["delete_target_asset_api_strategy_asset__symbol__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cash/{currency}/deposit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cash Deposit
         * @description v2 通用任意币种存款
         */
        post: operations["cash_deposit_api_cash__currency__deposit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Jobs Status
         * @description 所有 cron job 的配置 + APScheduler 下次触发时间。让 GUI 能看到"什么在静默跑
         */
        get: operations["get_jobs_status_api_jobs_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Insights
         * @description Dreaming 整合出的长期模式（memory/insights/*.md）
         */
        get: operations["get_insights_api_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regime/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Regime
         * @description 实时算指定 symbol 的市场 regime（牛/熊/震荡）+ 给 LLM 看的 brief
         */
        get: operations["get_regime_api_regime__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dreams/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dreams State
         * @description Dreaming 子系统当前状态：短期记忆 + 候选池 + 最近 events
         */
        get: operations["get_dreams_state_api_dreams_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pnl_history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pnl History
         * @description 原始 PnL 历史数据点（jobs/pnl_snapshot 工作日每 2h 写一条）
         */
        get: operations["get_pnl_history_api_pnl_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/committee_sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Committee Sessions
         * @description 历史委员会决议列表（memory/.committee/<date>/<symbol>.md），按时间倒序
         */
        get: operations["list_committee_sessions_api_committee_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Llm Usage
         * @description 每次 LLM 调用的明细（input/output tokens、延迟、成本、tool 调用数）
         */
        get: operations["get_llm_usage_api_llm_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Llm Summary
         * @description LLM 用量汇总：总调用 / 总 token / 总成本，按 agent_role 拆分
         */
        get: operations["get_llm_summary_api_llm_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data_sources/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Data Sources Health
         * @description 所有数据源的当前可达性 + 最后成功拉取时间。GUI 透明化"我们用什么数据决策"
         *
         *     数据源：yfinance NDQ.AX / GC=F / USDCNY=X / VIX / TNX；DB market_store；CommSec processed_emails
         */
        get: operations["get_data_sources_health_api_data_sources_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/verdict_review/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Verdict Review Data
         * @description 读 memory/.dreams/verdict_review.jsonl 原始数据（每条决议事后是否命中）
         */
        get: operations["get_verdict_review_data_api_verdict_review_data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/verdict_review/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Verdict Review Summary
         * @description 命中率汇总（按时间窗口 + 按 verdict 类型）。GUI marketing 主战场
         */
        get: operations["get_verdict_review_summary_api_verdict_review_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/verdict_review/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Verdict Review Report
         * @description 完整 docs/verdict_accuracy.md markdown 报告
         */
        get: operations["get_verdict_review_report_api_verdict_review_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regime_rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Regime Rules
         * @description 暴露 invest 项目所有「硬规则」+「LLM 提示词」给 GUI marketing 页
         *
         *     包含：
         *     - core/regime.py 阈值表
         *     - 4 个 agent 角色的 system prompt 全文
         *     - CIO sanity check 清单
         *     - 5 个可被 LLM 调用的 tool
         */
        get: operations["get_regime_rules_api_regime_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/tool_calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tool Calls
         * @description 每次 LLM 主动调 tool 的明细（agent_role / asset / tool_name / args / result preview / 耗时）。
         *     GUI 用此端点告诉用户 'AI 在 18:05 主动查了 multi_timeframe(NDQ.AX) 拿技术指标'
         */
        get: operations["get_tool_calls_api_agents_tool_calls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/committee_sessions/{date}/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Committee Session
         * @description 单个委员会决议完整 markdown
         */
        get: operations["get_committee_session_api_committee_sessions__date___symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cash/{currency}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cash Withdraw
         * @description v2 通用任意币种取款（默认禁止扣到负数 — PM 强烈要求；后续可加 force=true 显式越过）
         */
        post: operations["cash_withdraw_api_cash__currency__withdraw_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentPromptInfo
         * @description 单个 agent 角色的 prompt 配置
         */
        AgentPromptInfo: {
            /** Role */
            role: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Prompt Opening */
            prompt_opening?: string | null;
            /** Prompt Rebuttal */
            prompt_rebuttal?: string | null;
            /** Prompt Full */
            prompt_full?: string | null;
            /**
             * Temperature
             * @default 0.2
             */
            temperature: number;
            /**
             * Enable Tools
             * @default true
             */
            enable_tools: boolean;
            /** Notes */
            notes?: string[];
        };
        /**
         * AllocationsRequest
         * @description PUT /api/strategy/allocations body
         */
        AllocationsRequest: {
            /** Target Allocation Stock */
            target_allocation_stock: number;
            /** Target Allocation Cash */
            target_allocation_cash: number;
        };
        /**
         * CashSummary
         * @description 现金部分
         */
        CashSummary: {
            /**
             * Cny
             * @description CNY 现金
             */
            cny: number;
            /**
             * Aud
             * @description AUD 现金（CommSec 子弹）
             */
            aud: number;
        };
        /**
         * CashWriteRequest
         * @description POST /api/cash/{currency}/deposit | withdraw body
         */
        CashWriteRequest: {
            /** Amount */
            amount: number;
        };
        /**
         * CommitteeRunRequest
         * @description POST /api/committee/run body
         *
         *     v3 升级（2026-05-06）：
         *     - symbols 空 = 跑 strategy.target_assets 全部（多资产并行）
         *     - symbols 给了 = 跑指定的（单 / 多资产并行）
         *     - 与旧 daily_report.run() 区别：默认 max_debate_rounds=4 真讨论，不发邮件
         *     - cron 自动跑仍走 daily_report.run()（max=1 串行 + 邮件，节省成本）
         */
        CommitteeRunRequest: {
            /**
             * Note
             * @description 可选备注
             */
            note?: string | null;
            /**
             * Symbols
             * @description 资产列表；None = strategy.target_assets 全部
             */
            symbols?: string[] | null;
            /**
             * Max Debate Rounds
             * @description cross-challenge 上限。1=旧行为；4=真讨论（推荐）
             * @default 4
             */
            max_debate_rounds: number;
        };
        /**
         * CommitteeRunResponse
         * @description 触发后立即返回
         */
        CommitteeRunResponse: {
            /** Task Id */
            task_id: string;
            /**
             * Status
             * @constant
             */
            status: "queued";
            /** Started At */
            started_at: string;
            /** Poll Url */
            poll_url: string;
        };
        /** CommitteeSessionDetail */
        CommitteeSessionDetail: {
            /** Date */
            date: string;
            /** Symbol */
            symbol: string;
            /** Content */
            content: string;
        };
        /** CommitteeSessionSummary */
        CommitteeSessionSummary: {
            /** Date */
            date: string;
            /** Symbol */
            symbol: string;
            /** Verdict */
            verdict?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Dominant View */
            dominant_view?: string | null;
            /** Suggested Alloc Cny */
            suggested_alloc_cny?: number | null;
            /** File Path */
            file_path: string;
        };
        /** CommitteeSessionsResponse */
        CommitteeSessionsResponse: {
            /** Count */
            count: number;
            /** Sessions */
            sessions: components["schemas"]["CommitteeSessionSummary"][];
        };
        /**
         * CommitteeStatusResponse
         * @description GET /api/committee/{task_id} 响应
         */
        CommitteeStatusResponse: {
            /** Task Id */
            task_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "error";
            /** Started At */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
            /** Note */
            note?: string | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
            /** Phase */
            phase?: string | null;
            /** Last Event */
            last_event?: {
                [key: string]: unknown;
            } | null;
            /** Events */
            events?: {
                [key: string]: unknown;
            }[] | null;
            /** Symbol */
            symbol?: string | null;
            /** Max Debate Rounds */
            max_debate_rounds?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * DailyEntry
         * @description 单天 daily 日志（完整 markdown）
         */
        DailyEntry: {
            /** Date */
            date: string;
            /** Content */
            content: string;
        };
        /**
         * DailyResponse
         * @description /api/daily 响应
         */
        DailyResponse: {
            /** Count */
            count: number;
            /** Entries */
            entries: components["schemas"]["DailyEntry"][];
        };
        /** DataSourceHealth */
        DataSourceHealth: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Last Success At */
            last_success_at?: string | null;
            /**
             * Is Stale
             * @default false
             */
            is_stale: boolean;
            /** Sample Value */
            sample_value?: unknown | null;
            /** Error */
            error?: string | null;
        };
        /** DataSourcesHealthResponse */
        DataSourcesHealthResponse: {
            /** Sources */
            sources: components["schemas"]["DataSourceHealth"][];
        };
        /**
         * DepositRequest
         * @description POST /api/deposit body
         */
        DepositRequest: {
            /**
             * Currency
             * @description cny=人民币 / aud=澳元（NDQ 子弹）
             * @default cny
             * @enum {string}
             */
            currency: "cny" | "aud";
            /**
             * Amount
             * @description 正数金额
             */
            amount: number;
        };
        /** DreamEvent */
        DreamEvent: {
            /** Ts */
            ts: string;
            /** Phase */
            phase: string;
        } & {
            [key: string]: unknown;
        };
        /** DreamsStateResponse */
        DreamsStateResponse: {
            /** Short Term */
            short_term?: {
                [key: string]: unknown;
            } | null;
            /** Candidates */
            candidates?: {
                [key: string]: unknown;
            } | null;
            /** Recent Events */
            recent_events: components["schemas"]["DreamEvent"][];
        };
        /**
         * GoldHolding
         * @description 黄金持仓 + 实时估值
         */
        GoldHolding: {
            /**
             * Grams
             * @description 持仓克数
             */
            grams: number;
            /**
             * Avg Cost Cny Per Gram
             * @description 加权均价 CNY/g
             */
            avg_cost_cny_per_gram: number;
            /**
             * Spot Cny Per Gram
             * @description 实时现货价 CNY/g（yfinance）
             */
            spot_cny_per_gram?: number | null;
            /**
             * Bank Cny Per Gram
             * @description 浙商参考克价（含点差）
             */
            bank_cny_per_gram?: number | null;
            /**
             * Offset Pct
             * @description 浙商点差
             * @default 0
             */
            offset_pct: number;
            /**
             * Market Value Cny
             * @description 持仓现值 CNY
             */
            market_value_cny?: number | null;
            /**
             * Pnl Cny
             * @description 浮盈 CNY
             */
            pnl_cny?: number | null;
            /**
             * Is Stale
             * @description 价格来自 DB 兜底（yfinance 不可用）
             * @default false
             */
            is_stale: boolean;
        };
        /**
         * GoldOffsetRequest
         * @description POST /api/gold/offset body — 报当日浙商克价，反推点差
         */
        GoldOffsetRequest: {
            /**
             * Bank Price
             * @description 浙商当日克价 CNY/g
             */
            bank_price: number;
        };
        /**
         * GoldSetRequest
         * @description POST /api/gold/set body — 直接覆盖克数（不计流水，仅校正用）
         */
        GoldSetRequest: {
            /**
             * Grams
             * @description 目标克数（≥0）
             */
            grams: number;
        };
        /**
         * GoldTradeRequest
         * @description POST /api/gold/buy 和 /api/gold/sell 共用 body
         */
        GoldTradeRequest: {
            /**
             * Grams
             * @description 买入/卖出克数
             */
            grams: number;
            /**
             * Price Per Gram
             * @description 单价 CNY/g
             */
            price_per_gram: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description /api/health 响应
         */
        HealthResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /**
             * Service
             * @default invest-web-api
             */
            service: string;
            /** Timestamp */
            timestamp: string;
        };
        /**
         * HistoryResponse
         * @description /api/history 响应
         */
        HistoryResponse: {
            /** Count */
            count: number;
            /** Rows */
            rows: components["schemas"]["HistoryRow"][];
        };
        /**
         * HistoryRow
         * @description 单笔交易记录（兼容历史字段变化）
         */
        HistoryRow: {
            /** Ts */
            ts?: string | null;
            /** Ts Origin */
            ts_origin?: string | null;
            /** Action */
            action?: string | null;
            /** Symbol */
            symbol?: string | null;
            /** Units */
            units?: number | null;
            /** Price Per Unit */
            price_per_unit?: number | null;
            /** Total Amount */
            total_amount?: number | null;
            /** Currency */
            currency?: string | null;
            /** Channel */
            channel?: string | null;
            /** Source */
            source?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * HoldingCreateRequest
         * @description POST /api/holdings body — 新增持仓
         */
        HoldingCreateRequest: {
            /** Symbol */
            symbol: string;
            /**
             * Kind
             * @default equity
             * @enum {string}
             */
            kind: "equity" | "etf" | "metal" | "crypto" | "bond" | "fund" | "other";
            /**
             * Units
             * @default 0
             */
            units: number;
            /**
             * Unit Label
             * @default 股
             */
            unit_label: string;
            /**
             * Avg Cost
             * @default 0
             */
            avg_cost: number;
            /** Cost Currency */
            cost_currency: string;
            /** Channel */
            channel?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Yfinance Proxy */
            yfinance_proxy?: string | null;
            /**
             * Proxy Kind
             * @default direct
             * @enum {string}
             */
            proxy_kind: "direct" | "gold_cny_per_gram" | "fx_pair";
            /**
             * Is Tracking Only
             * @default false
             */
            is_tracking_only: boolean;
        };
        /**
         * HoldingPatchRequest
         * @description PUT /api/holdings/{symbol} body — 部分字段更新
         */
        HoldingPatchRequest: {
            /** Kind */
            kind?: ("equity" | "etf" | "metal" | "crypto" | "bond" | "fund" | "other") | null;
            /** Units */
            units?: number | null;
            /** Unit Label */
            unit_label?: string | null;
            /** Avg Cost */
            avg_cost?: number | null;
            /** Cost Currency */
            cost_currency?: string | null;
            /** Channel */
            channel?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Yfinance Proxy */
            yfinance_proxy?: string | null;
            /** Proxy Kind */
            proxy_kind?: ("direct" | "gold_cny_per_gram" | "fx_pair") | null;
            /** Is Tracking Only */
            is_tracking_only?: boolean | null;
        };
        /**
         * HoldingQuote
         * @description 单个 holding 的实时行情（通用化 v2 端点用）
         */
        HoldingQuote: {
            /** Price */
            price?: number | null;
            /** Currency */
            currency?: string | null;
            /** Unit */
            unit?: string | null;
            /** Last Updated */
            last_updated?: string | null;
            /**
             * Is Stale
             * @default false
             */
            is_stale: boolean;
            /** Extra */
            extra?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * HoldingV2
         * @description 单个 v2 holding（含静态字段 + 实时 quote + 计算的 P&L）
         */
        HoldingV2: {
            /** Symbol */
            symbol: string;
            /** Kind */
            kind: string;
            /** Units */
            units: number;
            /** Unit Label */
            unit_label: string;
            /** Avg Cost */
            avg_cost: number;
            /** Cost Currency */
            cost_currency: string;
            /** Channel */
            channel?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Yfinance Proxy */
            yfinance_proxy?: string | null;
            /**
             * Proxy Kind
             * @default direct
             */
            proxy_kind: string;
            /** Price Offset Pct */
            price_offset_pct?: number | null;
            /** Sell Fee Pct */
            sell_fee_pct?: number | null;
            /**
             * Is Tracking Only
             * @default false
             */
            is_tracking_only: boolean;
            quote?: components["schemas"]["HoldingQuote"] | null;
            /** Market Value */
            market_value?: number | null;
            /** Pnl */
            pnl?: number | null;
        };
        /**
         * HoldingsListResponse
         * @description GET /api/holdings 响应
         */
        HoldingsListResponse: {
            /** Cash */
            cash: {
                [key: string]: number;
            };
            /** Holdings */
            holdings: components["schemas"]["HoldingV2"][];
        };
        /** InsightItem */
        InsightItem: {
            /** Slug */
            slug: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Body */
            body: string;
        };
        /** InsightsResponse */
        InsightsResponse: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["InsightItem"][];
        };
        /** JobStatus */
        JobStatus: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Schedule */
            schedule: string;
            /** Timezone */
            timezone: string;
            /** Enabled */
            enabled: boolean;
            /** Next Run Time */
            next_run_time?: string | null;
        };
        /** JobsStatusResponse */
        JobsStatusResponse: {
            /** Jobs */
            jobs: components["schemas"]["JobStatus"][];
        };
        /** LlmRoleStats */
        LlmRoleStats: {
            /** Calls */
            calls: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cost Cny */
            cost_cny: number;
            /** Avg Latency Ms */
            avg_latency_ms: number;
        };
        /** LlmSummaryResponse */
        LlmSummaryResponse: {
            /** Total Calls */
            total_calls: number;
            /** Total Input Tokens */
            total_input_tokens: number;
            /** Total Output Tokens */
            total_output_tokens: number;
            /** Total Cost Cny */
            total_cost_cny: number;
            /** By Role */
            by_role: {
                [key: string]: components["schemas"]["LlmRoleStats"];
            };
        };
        /** LlmUsageRecord */
        LlmUsageRecord: {
            /** Ts */
            ts: string;
            /** Agent Role */
            agent_role: string;
            /** Asset */
            asset?: string | null;
            /** Round */
            round?: string | null;
            /**
             * Provider
             * @default deepseek
             */
            provider: string;
            /**
             * Model
             * @default deepseek-chat
             */
            model: string;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
            /**
             * Cost Cny
             * @default 0
             */
            cost_cny: number;
            /**
             * Tool Calls
             * @default 0
             */
            tool_calls: number;
            /**
             * Iteration
             * @default 0
             */
            iteration: number;
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** LlmUsageResponse */
        LlmUsageResponse: {
            /** Count */
            count: number;
            /** Records */
            records: components["schemas"]["LlmUsageRecord"][];
        };
        /**
         * NDQHolding
         * @description NDQ.AX 持仓 + 实时行情
         */
        NDQHolding: {
            /**
             * Shares
             * @description 持仓股数
             */
            shares: number;
            /**
             * Last Price Aud
             * @description 最新价 AUD
             */
            last_price_aud?: number | null;
            /**
             * Prev Close Aud
             * @description 前收 AUD
             */
            prev_close_aud?: number | null;
            /**
             * Day Change Pct
             * @description 日变化 %
             */
            day_change_pct?: number | null;
            /**
             * Last Updated
             * @description 行情日期 YYYY-MM-DD
             */
            last_updated?: string | null;
        };
        /** PnLHistoryPoint */
        PnLHistoryPoint: {
            /** Ts */
            ts: string;
            /** Total Pnl Pct */
            total_pnl_pct?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** PnLHistoryResponse */
        PnLHistoryResponse: {
            /** Count */
            count: number;
            /** Points */
            points: components["schemas"]["PnLHistoryPoint"][];
        };
        /**
         * PortfolioResponse
         * @description /api/portfolio 响应：完整持仓快照
         */
        PortfolioResponse: {
            cash: components["schemas"]["CashSummary"];
            gold: components["schemas"]["GoldHolding"];
            ndq: components["schemas"]["NDQHolding"];
        };
        /** RegimeResponse */
        RegimeResponse: {
            /** Symbol */
            symbol: string;
            /** Regime */
            regime: string;
            /** Reason */
            reason: string;
            /** Inputs */
            inputs: {
                [key: string]: unknown;
            };
            /** Strategy Hint */
            strategy_hint: string;
            /** Brief */
            brief: string;
        };
        /**
         * RegimeRulesResponse
         * @description Regime 判定硬规则 + 4 角色 prompt 全集（marketing 主战场）
         */
        RegimeRulesResponse: {
            /** Regime Thresholds */
            regime_thresholds: {
                [key: string]: number;
            };
            /** Regime Types */
            regime_types: string[];
            /** Regime Priority */
            regime_priority: string[];
            /** Verdict Options */
            verdict_options: string[];
            /** Sanity Checks */
            sanity_checks: string[];
            /** Agents */
            agents: components["schemas"]["AgentPromptInfo"][];
            /** Tools */
            tools: {
                [key: string]: unknown;
            }[];
        };
        /**
         * StrategyResponse
         * @description /api/strategy 响应
         */
        StrategyResponse: {
            /** Target Allocation Stock */
            target_allocation_stock: number;
            /** Target Allocation Cash */
            target_allocation_cash: number;
            /** Target Assets */
            target_assets: components["schemas"]["TargetAsset"][];
        };
        /**
         * StrategyWriteResponse
         * @description 策略写操作统一响应
         */
        StrategyWriteResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Target Allocation Stock */
            target_allocation_stock: number;
            /** Target Allocation Cash */
            target_allocation_cash: number;
            /** Target Assets */
            target_assets: {
                [key: string]: unknown;
            }[];
            /** Message */
            message: string;
        };
        /** SymbolSearchResponse */
        SymbolSearchResponse: {
            /** Count */
            count: number;
            /** Results */
            results: components["schemas"]["SymbolSearchResult"][];
        };
        /**
         * SymbolSearchResult
         * @description 单个搜索命中
         */
        SymbolSearchResult: {
            /** Symbol */
            symbol: string;
            /** Shortname */
            shortname?: string | null;
            /** Longname */
            longname?: string | null;
            /** Exchange */
            exchange?: string | null;
            /** Quote Type */
            quote_type?: string | null;
        };
        /**
         * TargetAsset
         * @description strategy.md 中的单个目标资产
         */
        TargetAsset: {
            /** Symbol */
            symbol: string;
            /** Display Name */
            display_name?: string | null;
            /** Channel */
            channel?: string | null;
            /**
             * Max Single Invest Cny
             * @default 0
             */
            max_single_invest_cny: number;
            /** Price Offset Pct */
            price_offset_pct?: number | null;
            /** Sell Fee Pct */
            sell_fee_pct?: number | null;
        };
        /**
         * TargetAssetCreate
         * @description POST /api/strategy/asset body
         */
        TargetAssetCreate: {
            /** Symbol */
            symbol: string;
            /** Display Name */
            display_name?: string | null;
            /** Channel */
            channel?: string | null;
            /** Max Single Invest Cny */
            max_single_invest_cny: number;
            /** Price Offset Pct */
            price_offset_pct?: number | null;
            /** Sell Fee Pct */
            sell_fee_pct?: number | null;
            /** Extra */
            extra?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * TargetAssetPatch
         * @description PUT /api/strategy/asset/{symbol} body — 全字段可选，仅更新提供的字段
         */
        TargetAssetPatch: {
            /** Display Name */
            display_name?: string | null;
            /** Channel */
            channel?: string | null;
            /** Max Single Invest Cny */
            max_single_invest_cny?: number | null;
            /** Price Offset Pct */
            price_offset_pct?: number | null;
            /** Sell Fee Pct */
            sell_fee_pct?: number | null;
        };
        /** ToolCallRecord */
        ToolCallRecord: {
            /** Ts */
            ts: string;
            /** Agent Role */
            agent_role: string;
            /** Asset */
            asset?: string | null;
            /** Round */
            round?: string | null;
            /** Tool Name */
            tool_name: string;
            /** Arguments */
            arguments?: {
                [key: string]: unknown;
            };
            /**
             * Result Preview
             * @default
             */
            result_preview: string;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
            /**
             * Iteration
             * @default 0
             */
            iteration: number;
        } & {
            [key: string]: unknown;
        };
        /** ToolCallsResponse */
        ToolCallsResponse: {
            /** Count */
            count: number;
            /** Records */
            records: components["schemas"]["ToolCallRecord"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerdictReviewDataResponse */
        VerdictReviewDataResponse: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["VerdictReviewItem"][];
        };
        /**
         * VerdictReviewItem
         * @description 单条 verdict review 记录（实际 schema 字段类型多样，宽松接受）
         */
        VerdictReviewItem: {
            /** Date */
            date: string;
            /** Asset */
            asset?: string | null;
            /** Verdict */
            verdict?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Expected Direction */
            expected_direction?: string | null;
            /** Macro Shock */
            macro_shock?: {
                [key: string]: unknown;
            } | null;
            /** Source */
            source?: string | null;
            /** Actual Returns */
            actual_returns?: {
                [key: string]: number;
            } | null;
            /** Hits */
            hits?: {
                [key: string]: boolean;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * VerdictReviewReportResponse
         * @description docs/verdict_accuracy.md 完整内容
         */
        VerdictReviewReportResponse: {
            /** Exists */
            exists: boolean;
            /** Generated At */
            generated_at?: string | null;
            /** Content */
            content?: string | null;
        };
        /**
         * VerdictReviewSummary
         * @description 命中率汇总
         */
        VerdictReviewSummary: {
            /** Total */
            total: number;
            /** By Window */
            by_window: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** By Verdict */
            by_verdict: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Directional Only Hit Rate */
            directional_only_hit_rate?: number | null;
            /** Has Report Md */
            has_report_md: boolean;
        };
        /**
         * WithdrawRequest
         * @description POST /api/withdraw body
         */
        WithdrawRequest: {
            /**
             * Currency
             * @description cny=人民币 / aud=澳元
             * @default cny
             * @enum {string}
             */
            currency: "cny" | "aud";
            /**
             * Amount
             * @description 正数金额
             */
            amount: number;
        };
        /**
         * WriteResponse
         * @description 写操作统一响应：返回新写入字段 + history 是否记录
         */
        WriteResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Cash Cny */
            cash_cny?: number | null;
            /** Aud Cash */
            aud_cash?: number | null;
            /** Gold Grams */
            gold_grams?: number | null;
            /** Gold Avg Cost Cny Per Gram */
            gold_avg_cost_cny_per_gram?: number | null;
            /**
             * History Appended
             * @default false
             */
            history_appended: boolean;
            /** Message */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_portfolio_api_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
        };
    };
    get_holdings_api_holdings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingsListResponse"];
                };
            };
        };
    };
    add_holding_api_holdings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldingCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_holding_api_holdings__symbol__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldingPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_holding_api_holdings__symbol__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_symbols_api_symbols_search_get: {
        parameters: {
            query: {
                /** @description 搜索关键词 */
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymbolSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_strategy_api_strategy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyResponse"];
                };
            };
        };
    };
    get_gold_api_gold_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoldHolding"];
                };
            };
        };
    };
    get_ndq_api_ndq_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NDQHolding"];
                };
            };
        };
    };
    get_history_api_history_get: {
        parameters: {
            query?: {
                /** @description 返回最近 N 笔（按时间倒序） */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pnl_chart_api_pnl_chart_svg_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_daily_api_daily_get: {
        parameters: {
            query?: {
                /** @description 最近 N 天 */
                since?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deposit_api_deposit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepositRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    withdraw_api_withdraw_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WithdrawRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gold_buy_api_gold_buy_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoldTradeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gold_sell_api_gold_sell_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoldTradeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gold_set_api_gold_set_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoldSetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gold_offset_api_gold_offset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoldOffsetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    committee_run_api_committee_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CommitteeRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitteeRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    committee_status_api_committee__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitteeStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    committee_live_api_committee_live__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_allocations_api_strategy_allocations_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllocationsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyWriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_target_asset_api_strategy_asset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetAssetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyWriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_target_asset_api_strategy_asset__symbol__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetAssetPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyWriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_target_asset_api_strategy_asset__symbol__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyWriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cash_deposit_api_cash__currency__deposit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                currency: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CashWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_jobs_status_api_jobs_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsStatusResponse"];
                };
            };
        };
    };
    get_insights_api_insights_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsResponse"];
                };
            };
        };
    };
    get_regime_api_regime__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegimeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dreams_state_api_dreams_state_get: {
        parameters: {
            query?: {
                event_limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DreamsStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pnl_history_api_pnl_history_get: {
        parameters: {
            query?: {
                /** @description 返回最近 N 条快照 */
                since?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PnLHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_committee_sessions_api_committee_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitteeSessionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_llm_usage_api_llm_usage_get: {
        parameters: {
            query?: {
                since?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmUsageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_llm_summary_api_llm_summary_get: {
        parameters: {
            query?: {
                since_records?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_data_sources_health_api_data_sources_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataSourcesHealthResponse"];
                };
            };
        };
    };
    get_verdict_review_data_api_verdict_review_data_get: {
        parameters: {
            query?: {
                since?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerdictReviewDataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_verdict_review_summary_api_verdict_review_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerdictReviewSummary"];
                };
            };
        };
    };
    get_verdict_review_report_api_verdict_review_report_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerdictReviewReportResponse"];
                };
            };
        };
    };
    get_regime_rules_api_regime_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegimeRulesResponse"];
                };
            };
        };
    };
    get_tool_calls_api_agents_tool_calls_get: {
        parameters: {
            query?: {
                since?: number;
                /** @description 过滤特定资产 symbol */
                asset?: string | null;
                /** @description 过滤特定 agent role */
                role?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolCallsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_committee_session_api_committee_sessions__date___symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitteeSessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cash_withdraw_api_cash__currency__withdraw_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                currency: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CashWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
